export type ChampionsLearnset = {
  pokemonSlug: string;
  pokemonJa: string;
  moves: string[];
};

const LEARNSET_MOVE_TYPE_FALLBACK: Record<string, string> = {
  "ギガインパクト": "normal",
  "すてみタックル": "normal",
  "あばれる": "normal",
  "のしかかり": "normal",
  "からげんき": "normal",
  "はかいこうせん": "normal",
  "りんしょう": "normal",
  "いびき": "normal",
  "てだすけ": "normal",
  "ねごと": "normal",
  "こらえる": "normal",
  "こわいかお": "normal",
  "まもる": "normal",
  "みがわり": "normal",
  "つるぎのまい": "steel",
  "ほのおのキバ": "fire",
  "だいもんじ": "fire",
  "かえんほうしゃ": "fire",
  "にほんばれ": "fire",
  "アクアブレイク": "water",
  "なみのり": "water",
  "あまごい": "water",
  "かみなりのキバ": "electric",
  "つばめがえし": "flying",
  "ストーンエッジ": "rock",
  "いわなだれ": "rock",
  "がんせきふうじ": "rock",
  "パワージェム": "rock",
  "ステルスロック": "rock",
  "すなあらし": "rock",
  "どくづき": "poison",
  "じしん": "ground",
  "あなをほる": "ground",
  "じだんだ": "ground",
  "じならし": "ground",
  "すなじごく": "ground",
  "だいちのちから": "ground",
  "ねっさのだいち": "ground",
  "マッドショット": "ground",
  "まきびし": "ground",
  "かわらわり": "fighting",
  "ねむる": "psychic",
  "シャドークロー": "ghost",
  "げきりん": "dragon",
  "ドラゴンダイブ": "dragon",
  "ドラゴンクロー": "dragon",
  "ワイドブレイカー": "dragon",
  "ドラゴンテール": "dragon",
  "スケイルショット": "dragon",
  "りゅうせいぐん": "dragon",
  "りゅうのはどう": "dragon",
  "ドラゴンエール": "dragon",
  "かみくだく": "dark",
  "ぶんまわす": "dark",
  "かみつく": "dark",
  "なげつける": "dark",
  "アイアンテール": "steel",
  "アイアンヘッド": "steel",
};

const PRIORITY_MOVES: Record<string, number> = {
  "でんこうせっか": 1,
  "しんくうは": 1,
  "アクアジェット": 1,
  "ふいうち": 1,
  "こおりのつぶて": 1,
  "バレットパンチ": 1,
  "かげうち": 1,
  "しんそく": 2,
  "ねこだまし": 3,
  "であいがしら": 2,
  "フェイント": 2,
  "てだすけ": 5,
  "まもる": 4,
  "みきり": 4,
  "トーチカ": 4,
  "キングシールド": 4,
  "こらえる": 4,
};

const LEARNSETS: Record<string, ChampionsLearnset> = {
  garchomp: {
    pokemonSlug: "garchomp",
    pokemonJa: "ガブリアス",
    moves: [
      "ギガインパクト",
      "すてみタックル",
      "あばれる",
      "のしかかり",
      "からげんき",
      "はかいこうせん",
      "りんしょう",
      "いびき",
      "てだすけ",
      "ねごと",
      "こらえる",
      "こわいかお",
      "まもる",
      "みがわり",
      "つるぎのまい",
      "ほのおのキバ",
      "だいもんじ",
      "かえんほうしゃ",
      "にほんばれ",
      "アクアブレイク",
      "なみのり",
      "あまごい",
      "かみなりのキバ",
      "つばめがえし",
      "ストーンエッジ",
      "いわなだれ",
      "がんせきふうじ",
      "パワージェム",
      "ステルスロック",
      "すなあらし",
      "どくづき",
      "じしん",
      "あなをほる",
      "じだんだ",
      "じならし",
      "すなじごく",
      "だいちのちから",
      "ねっさのだいち",
      "マッドショット",
      "まきびし",
      "かわらわり",
      "ねむる",
      "シャドークロー",
      "げきりん",
      "ドラゴンダイブ",
      "ドラゴンクロー",
      "ワイドブレイカー",
      "ドラゴンテール",
      "スケイルショット",
      "りゅうせいぐん",
      "りゅうのはどう",
      "ドラゴンエール",
      "かみくだく",
      "ぶんまわす",
      "かみつく",
      "なげつける",
      "アイアンテール",
      "アイアンヘッド",
    ],
  },
};

export function getChampionsLearnset(pokemonSlug: string): ChampionsLearnset | null {
  return LEARNSETS[pokemonSlug] ?? null;
}

export function getPriorityMoves(learnset: ChampionsLearnset): Array<{ name: string; priority: number }> {
  return learnset.moves
    .filter((move) => move in PRIORITY_MOVES)
    .map((move) => ({ name: move, priority: PRIORITY_MOVES[move] }))
    .sort((a, b) => b.priority - a.priority || a.name.localeCompare(b.name, "ja"));
}

export function getLearnsetMoveTypeFallback(move: string): string | null {
  return LEARNSET_MOVE_TYPE_FALLBACK[move] ?? null;
}
